### ISSUE TITLE
Hey budy i need help 

### ISSUE THREAD

**Issue by adarshchri** [SBDeveloper10/movies-downloader-bot#21]
async def movie_name(update: Update, context: ContextTypes.DEFAULT_TYPE):
    search_results = await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text='Processing .....',
    )
    
    argument = context.args
    argument_text = " ".join(argument)
    base_url = f"http://127.0.0.1:5000/search?name={argument_text}"
    movie_result = requests.get(base_url).json()
    keyboard = []
    for movies in movie_result:
        movie_name = movies['name']
        movie_size = movies['size']
        imdb_id = movies['uploader']
        movie_hash = movies['hash']
        movie_category = movies['category']
        button_text = f'({movie_size}) - {movie_name}'
        button_callback = f'{movie_hash}'

        button = InlineKeyboardButton(
            text=button_text, callback_data=button_callback,
        )
        keyboard.append([button]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text='Select ...',
        reply_markup=reply_markup
    )

In this when I pass the first movie name it returns the movie work fine (eg: FIrst have 4 inline keyboards)
but when I pass the second movie name it return the inline keyboard with the first result and the second also (eg : second should have 4 inline keyboard but with the addition of first keyboard also it give me 8 keyboard)

**Comment by shrirampachpor** [comment]
Hi my bot also not working after changing the url to new one that showing
me message like"Sorry 🙏, No Result Found!
Check If You Have Misspelled The Movie Name." Is there any fix please tell
me.🥺🙏🏻.
